CREATE TABLE members (
    id               NUMBER(19,0)       NOT NULL,
    username         VARCHAR2(30 CHAR)  NOT NULL,
    display_name     VARCHAR2(30 CHAR),
    image_url        VARCHAR2(255 CHAR),
    provider         VARCHAR2(255 CHAR) CHECK (provider IN ('KAKAO', 'ULALA')),
    provider_user_id VARCHAR2(255 CHAR),
    member_level     NUMBER(10,0) DEFAULT 1 NOT NULL,
    point            NUMBER(19,0) DEFAULT 0 NOT NULL,
    exp              NUMBER(19,0) DEFAULT 0 NOT NULL,
    deleted          NUMBER(1,0)        NOT NULL CHECK (deleted IN (0, 1)),
    deleted_at       TIMESTAMP(6),
    created_at       TIMESTAMP(6)       NOT NULL,
    created_by       VARCHAR2(255 CHAR) NOT NULL,
    modified_at      TIMESTAMP(6)       NOT NULL,
    modified_by      VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_members_username ON members (username);
CREATE INDEX idx_members_provider_user_id ON members (provider, provider_user_id);

CREATE TABLE tasks (
    id              NUMBER(19, 0)         NOT NULL,
    member_id       NUMBER(19, 0)         NOT NULL,
    title           VARCHAR2(100 CHAR)    NOT NULL,
    description     VARCHAR2(4000 CHAR),
    status          VARCHAR2(255 CHAR)    NOT NULL CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE', 'ON_HOLD')),
    display_order   NUMBER(10, 0) DEFAULT 1 NOT NULL,
    start_at        TIMESTAMP(6),
    end_at          TIMESTAMP(6),
    due_at          TIMESTAMP(6),
    deleted         NUMBER(1, 0)          NOT NULL CHECK (deleted IN (0, 1)),
    deleted_at      TIMESTAMP(6),
    created_at      TIMESTAMP(6)          NOT NULL,
    created_by      VARCHAR2(255 CHAR)    NOT NULL,
    modified_at     TIMESTAMP(6)          NOT NULL,
    modified_by     VARCHAR2(255 CHAR)    NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_tasks_member_id_deleted_id ON tasks (member_id, deleted, id DESC);
CREATE INDEX idx_tasks_member_id_deleted_created  ON tasks (member_id, deleted, created_at);
CREATE INDEX idx_tasks_member_id_deleted_modified ON tasks (member_id, deleted, modified_at);

CREATE TABLE rewards (
    id            NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1 NOCACHE),
    member_id     NUMBER(19, 0) NOT NULL,
    source_id     NUMBER(19, 0),
    source_type   VARCHAR2(255 CHAR)
                  CHECK (source_type IN ('TASK', 'EVENT')),
    point         NUMBER(19, 0) NOT NULL,
    exp           NUMBER(19, 0) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    created_by    VARCHAR2(255 CHAR) NOT NULL,
    modified_at   TIMESTAMP(6) NOT NULL,
    modified_by   VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_rewards_member_id_source_id_source_type ON rewards (member_id, source_id, source_type);

CREATE TABLE characters (
    id           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1 NOCACHE),
    member_id    NUMBER(19,0)        NOT NULL,
    role_model   VARCHAR2(30 CHAR)   NOT NULL,
    created_at   TIMESTAMP(6)        NOT NULL,
    created_by   VARCHAR2(255 CHAR)  NOT NULL,
    modified_at  TIMESTAMP(6)        NOT NULL,
    modified_by  VARCHAR2(255 CHAR)  NOT NULL,
    deleted      NUMBER(1,0)         NOT NULL
                     CHECK (deleted IN (0, 1)),
    deleted_at   TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX idx_characters_deleted_member_role ON characters (deleted, member_id, role_model);
